#!/data/data/com.termux/files/usr/bin/bash

ROOT="/storage/emulated/0/AppProjects"

echo "Cleaning junk..."

find "$ROOT" -type d \( -name "build" -o -name ".gradle" -o -name "tmp" \) -exec rm -rf {} + 2>/dev/null

echo "Boost complete"
